# baseURL = 'https://github.com/greencloud-tang/chinese-business-directory'
languageCode = 'en-us'
title = 'The 1913 Transnational Chinese Business Directory: A Geo-Linguistic Exploration'
relativeURLs = false
[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-blue"
recent_posts_number = 3
copyright_author = "Tang, H"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

 # Define the "About" page
[[menu.main]]
    name = "About"
    url = "/ "
    weight = 10 # Place it first
  
  # Define the "Directory" page
[[menu.main]]
    name = "Directory"
    url = "/directory/"
    weight = 20
    
  # Define the "location list" page
  # This is the one you want to customize
  [[menu.main]]
    name = "Location List"
    url = "/location-list/"
    weight = 30 # Place it third

  # Define the "Patterns" page
  [[menu.main]]
    name = "Patterns"
    url = "/patterns/"
    weight = 40 # Place it fourth


  # Define the "Contact" page
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 50 # Place it last

  
